#!/usr/bin/env python

import re

def tableize(sql):
    return re.sub(r'([a-z])([A-Z])', r'\1_\2', sql).lower()


def add_public_schema(sql):
    return re.sub(r'^\s*create table (\w+)\b', r'drop table if exists public.\1 cascade;\ncreate table public.\1', sql, 0, re.MULTILINE)


def replace_identity(sql):
    return re.sub(r'identity', 'generated by default as identity', sql, 0, re.MULTILINE)


def replace_nvarchar(sql):
    it = re.finditer(r'nvarchar\((\d+)\)', sql, re.MULTILINE)
    ns = sql
    for m in it:
        l = m.group(1)
        nl = int(l) * 2
        ns = re.sub(r'nvarchar\(\d+\)', 'varchar(' + str(nl) + ')', ns, 1, re.MULTILINE)

    return ns


def replace_nchar(sql):
    it = re.finditer(r'nchar\((\d+)\)', sql, re.MULTILINE)
    ns = sql
    for m in it:
        l = m.group(1)
        nl = int(l) * 2
        ns = re.sub(r'nchar\(\d+\)', 'char(' + str(nl) + ')', ns, 1, re.MULTILINE)

    return ns


def replace_varbinary_max(sql):
    return re.sub(r'varbinary\(max\)', 'bytea', sql, 0, re.MULTILINE)


def replace_datetime(sql):
    return re.sub(r'datetime', 'timestamp', sql, 0, re.MULTILINE)


def replace_delim(sql):
    return re.sub(r'\ngo', ';\n\n', sql, 0, re.MULTILINE)


ms_sql = """
create table DimPromotion
(
    PromotionKey             int identity
        constraint PK_DimPromotion_PromotionKey
            primary key,
    PromotionAlternateKey    int
        constraint AK_DimPromotion_PromotionAlternateKey
            unique,
    EnglishPromotionName     nvarchar(255),
    SpanishPromotionName     nvarchar(255),
    FrenchPromotionName      nvarchar(255),
    DiscountPct              float,
    EnglishPromotionType     nvarchar(50),
    SpanishPromotionType     nvarchar(50),
    FrenchPromotionType      nvarchar(50),
    EnglishPromotionCategory nvarchar(50),
    SpanishPromotionCategory nvarchar(50),
    FrenchPromotionCategory  nvarchar(50),
    StartDate                datetime not null,
    EndDate                  datetime,
    MinQty                   int,
    MaxQty                   int
)
go
"""


print(replace_delim(replace_datetime(replace_varbinary_max(replace_nchar(replace_nvarchar(replace_identity(add_public_schema(tableize(ms_sql)))))))))
